### ISSUE TITLE
Could not find a valid Docker environment

### ISSUE THREAD

**Issue by jose** [EMResearch/EMB#37]
Hi @arcuri82,

I'm getting the following error when I try to generate tests for `patio-api`. 

```
 _____          ___  ___          _
|  ___|         |  \/  |         | |
| |____   _____ | .  . | __ _ ___| |_ ___ _ __
|  __\ \ / / _ \| |\/| |/ _` / __| __/ _ \ '__|
| |___\ V / (_) | |  | | (_| \__ \ ||  __/ |
\____/ \_/ \___/\_|  |_/\__,_|___/\__\___|_|

                    
* EvoMaster version: 1.4.1-SNAPSHOT
* WARNING: The option to turn on Executive Summary is only meaningful when clustering is turned on (--testSuiteSplitType CLUSTERING). The option has been deactivated for this run, to prevent a crash.
* WARNING: Using deprecated option 'testSuiteFileName'
17:44:56.959 [main] WARN  o.e.c.r.service.RemoteController - Failed to change running state of the SUT. HTTP status 500. Error: 'Could not find a valid Docker environment. Please see logs and check configuration
* [ERROR] ERROR related to the system under test: Failed to start the SUT
  For white-box testing, look at the logs of the EvoMaster Driver to help debugging this problem.
```

```
Started controller server on: http://localhost:10010/controller/api
Going to start the SUT
17:44:26.185 [qtp1234250905-22] WARN  o.t.u.TestcontainersConfiguration - Attempted to read Testcontainers configuration file at file:/home/jcmcampos/.testcontainers.properties but the file was not found. Exception message: FileNotFoundException: /home/jcmcampos/.testcontainers.properties (No such file or directory)
17:44:26.208 [qtp1234250905-22] INFO  o.t.d.DockerMachineClientProviderStrategy - docker-machine executable was not found on PATH ([/home/jcmcampos/jdk-11/bin, /home/jcmcampos/.local/bin, /home/jcmcampos/bin, /home/jcmcampos/.local/bin, /home/jcmcampos/bin, /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /usr/local/games, /snap/bin])
17:44:56.892 [qtp1234250905-22] ERROR o.t.d.DockerClientProviderStrategy - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
17:44:56.892 [qtp1234250905-22] ERROR o.t.d.DockerClientProviderStrategy -     UnixSocketClientProviderStrategy: failed with exception TimeoutException (Timeout waiting for result with exception). Root cause IOException (native connect() failed : Permission denied)
17:44:56.892 [qtp1234250905-22] ERROR o.t.d.DockerClientProviderStrategy - As no valid configuration was found, execution cannot continue
ERROR - Could not find a valid Docker environment. Please see logs and check configuration
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:215)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:207)
        at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:136)
        at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:178)
        at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
        at org.testcontainers.LazyDockerClient.authConfig(LazyDockerClient.java:12)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:310)
        at em.external.patio.ExternalEvoMasterController.preStart(ExternalEvoMasterController.java:142)
        at org.evomaster.client.java.controller.ExternalSutController.startSut(ExternalSutController.java:153)
        at org.evomaster.client.java.controller.internal.EMController.lambda$runSut$15(EMController.java:327)
        at org.evomaster.client.java.controller.internal.EMController.noKillSwitch(EMController.java:125)
        at org.evomaster.client.java.controller.internal.EMController.runSut(EMController.java:327)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at shaded.org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at shaded.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
        at shaded.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
        at shaded.org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
        at shaded.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
        at shaded.org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
        at shaded.org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
        at shaded.org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
        at shaded.org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
        at shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at shaded.org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
        at shaded.org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
        at shaded.org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
        at shaded.org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
        at shaded.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
        at shaded.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
        at shaded.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
        at shaded.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
        at shaded.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551)
        at shaded.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at shaded.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1369)
        at shaded.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at shaded.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
        at shaded.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at shaded.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284)
        at shaded.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at shaded.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at shaded.org.eclipse.jetty.server.Server.handle(Server.java:501)
        at shaded.org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
        at shaded.org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
        at shaded.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
        at shaded.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at shaded.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at shaded.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at shaded.org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at shaded.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at shaded.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at shaded.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at shaded.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
        at shaded.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at shaded.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

I can understand that the `/home/jcmcampos/.testcontainers.properties` file does not exist, but what should the content of that file be?

--
Best,
Jose

**Comment by jose** [comment]
FYI, I'm getting the exact same error for `ocvn-rest` and `timbuctoo`.

**Comment by arcuri82** [comment]
Hi,
 haven't seen such issue before.
You have installed `Docker`, isn't it?

**Comment by arcuri82** [comment]
if you are using Windows, might have to reboot the machine (Docker on Windows has some known issues)

**Comment by jose** [comment]
I'm using linux and I do have docker installed (v20.10.7).

**Comment by arcuri82** [comment]
is Docker working when doing a `docker ps`? 

we have been running EM on Linux with no problem... maybe you can try to restart docker?

**Comment by jose** [comment]
> is Docker working when doing a `docker ps`?

No.  Somehow my user was not a member of the `docker` group and therefore had no permission to, e.g., run `docker ps`.  I've just added my user to the `docker` group with `sudo usermod -aG docker $USER` and re-executed EvoMaster on `patio-api`.  It is now running as expected.

PS: the content of the supposed missing file `/home/jcmcampos/.testcontainers.properties` is currently
```
$ cat /home/jcmcampos/.testcontainers.properties
#Modified by Testcontainers
#Tue Apr 05 08:12:41 WEST 2022
docker.client.strategy=org.testcontainers.dockerclient.UnixSocketClientProviderStrategy
```


--
Best,
Jose

**Comment by arcuri82** [comment]
good to hear ;) i ll close this issue then
